"""Initial VMS database schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False, server_default='viewer'),
        sa.CheckConstraint("role IN ('admin', 'viewer')", name='check_users_role'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('email'),
    )
    
    op.create_index('idx_users_username', 'users', ['username'])
    op.create_index('idx_users_email', 'users', ['email'])
    
    op.create_table(
        'cameras',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('rtsp_url', sa.String(length=500), nullable=False),
        sa.Column('onvif_host', sa.String(length=100), nullable=True),
        sa.Column('onvif_port', sa.Integer(), nullable=True, server_default='80'),
        sa.Column('onvif_username', sa.String(length=50), nullable=True),
        sa.Column('onvif_password', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='offline'),
        sa.Column('recording_mode', sa.String(length=20), nullable=False, server_default='motion'),
        sa.Column('detection_enabled', sa.Integer(), nullable=False, server_default='1'),
        sa.CheckConstraint("detection_enabled IN (0, 1)", name='check_cameras_detection_enabled'),
        sa.Column('detection_confidence', sa.Float(), nullable=False, server_default='0.5'),
        sa.CheckConstraint("detection_confidence >= 0 AND detection_confidence <= 1", name='check_cameras_detection_confidence'),
        sa.Column('resolution_width', sa.Integer(), nullable=True),
        sa.Column('resolution_height', sa.Integer(), nullable=True),
        sa.Column('codec', sa.String(length=20), nullable=True),
        sa.Column('fps', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.Column('updated_at', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.CheckConstraint("status IN ('online', 'offline', 'error')", name='check_cameras_status'),
        sa.CheckConstraint("recording_mode IN ('continuous', 'motion', 'scheduled')", name='check_cameras_recording_mode'),
    )
    
    op.create_index('idx_cameras_status', 'cameras', ['status'])
    op.create_index('idx_cameras_name', 'cameras', ['name'])
    
    op.create_table(
        'recordings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('camera_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('recording_type', sa.String(length=20), nullable=False, server_default='motion'),
        sa.Column('start_time', sa.String(), nullable=False),
        sa.Column('end_time', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('duration', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_encrypted', sa.Integer(), nullable=False, server_default='0'),
        sa.CheckConstraint("is_encrypted IN (0, 1)", name='check_recordings_is_encrypted'),
        sa.Column('encryption_key', sa.String(length=255), nullable=True),
        sa.Column('codec', sa.String(length=20), nullable=True),
        sa.Column('resolution_width', sa.Integer(), nullable=True),
        sa.Column('resolution_height', sa.Integer(), nullable=True),
        sa.Column('bitrate', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
        sa.CheckConstraint("recording_type IN ('continuous', 'motion', 'scheduled')", name='check_recordings_recording_type'),
    )
    
    op.create_index('idx_recordings_camera_id', 'recordings', ['camera_id'])
    op.create_index('idx_recordings_start_time', 'recordings', ['start_time'])
    op.create_index('idx_recordings_camera_start', 'recordings', ['camera_id', 'start_time'])
    op.create_index('idx_recordings_recording_type', 'recordings', ['recording_type'])
    
    op.create_table(
        'video_metadata',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recording_id', sa.Integer(), nullable=False, unique=True),
        sa.Column('thumbnails', sa.Text(), nullable=True),
        sa.Column('detected_objects', sa.Text(), nullable=True),
        sa.Column('motion_events', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('recording_id'),
    )
    
    op.create_index('idx_video_metadata_recording_id', 'video_metadata', ['recording_id'])
    
    op.create_table(
        'events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('camera_id', sa.Integer(), nullable=True),
        sa.Column('recording_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='new'),
        sa.Column('push_sent', sa.Integer(), nullable=False, server_default='0'),
        sa.CheckConstraint("push_sent IN (0, 1)", name='check_events_push_sent'),
        sa.CheckConstraint("event_type IN ('motion_detected', 'person_detected', 'camera_offline', 'camera_error', 'storage_full', 'system_error')", name='check_events_event_type'),
        sa.CheckConstraint("status IN ('new', 'acknowledged', 'resolved')", name='check_events_status'),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='SET NULL'),
    )
    
    op.create_index('idx_events_camera_id', 'events', ['camera_id'])
    op.create_index('idx_events_timestamp', 'events', ['timestamp'])
    op.create_index('idx_events_event_type', 'events', ['event_type'])
    op.create_index('idx_events_status', 'events', ['status'])
    op.create_index('idx_events_camera_timestamp', 'events', ['camera_id', 'timestamp'])
    
    op.create_table(
        'logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('level', sa.String(length=10), nullable=False),
        sa.Column('component', sa.String(length=50), nullable=False),
        sa.Column('message', sa.String(length=1000), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.CheckConstraint("level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')", name='check_logs_level'),
    )
    
    op.create_index('idx_logs_level', 'logs', ['level'])
    op.create_index('idx_logs_component', 'logs', ['component'])
    op.create_index('idx_logs_timestamp', 'logs', ['timestamp'])
    op.create_index('idx_logs_level_timestamp', 'logs', ['level', 'timestamp'])
    
    op.create_table(
        'settings',
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('updated_at', sa.String(), nullable=False, server_default=sa.text("(datetime('now'))"),
        sa.CheckConstraint("category IN ('storage', 'recording', 'detection', 'notification', 'system', 'auth')", name='check_settings_category'),
        sa.PrimaryKeyConstraint('key'),
    )
    
    op.create_index('idx_settings_category', 'settings', ['category'])
    
    op.create_table(
        'schedules',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('camera_id', sa.Integer(), nullable=False),
        sa.Column('days_of_week', sa.Text(), nullable=False),
        sa.Column('start_time', sa.String(length=5), nullable=False),
        sa.Column('end_time', sa.String(length=5), nullable=False),
        sa.Column('record_type', sa.String(length=20), nullable=False, server_default='continuous'),
        sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'),
        sa.CheckConstraint("record_type IN ('continuous', 'motion')", name='check_schedules_record_type'),
        sa.CheckConstraint("is_active IN (0, 1)", name='check_schedules_is_active'),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    )
    
    op.create_index('idx_schedules_camera_id', 'schedules', ['camera_id'])
    op.create_index('idx_schedules_is_active', 'schedules', ['is_active'])


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schedules_is_active', 'schedules')
    op.drop_index('idx_schedules_camera_id', 'schedules')
    
    op.drop_table('schedules')
    
    op.drop_index('idx_settings_category', 'settings')
    
    op.drop_table('settings')
    
    op.drop_index('idx_logs_level_timestamp', 'logs')
    op.drop_index('idx_logs_component', 'logs')
    op.drop_index('idx_logs_timestamp', 'logs')
    op.drop_index('idx_logs_level', 'logs')
    
    op.drop_table('logs')
    
    op.drop_index('idx_events_camera_timestamp', 'events')
    op.drop_index('idx_events_status', 'events')
    op.drop_index('idx_events_event_type', 'events')
    op.drop_index('idx_events_timestamp', 'events')
    op.drop_index('idx_events_camera_id', 'events')
    
    op.drop_index('idx_recordings_recording_type', 'recordings')
    op.drop_index('idx_recordings_camera_start', 'recordings')
    op.drop_index('idx_recordings_start_time', 'recordings')
    op.drop_index('idx_recordings_camera_id', 'recordings')
    
    op.drop_table('video_metadata')
    op.drop_index('idx_video_metadata_recording_id', 'video_metadata')
    
    op.drop_table('recordings')
    
    op.drop_index('idx_cameras_name', 'cameras')
    op.drop_index('idx_cameras_status', 'cameras')
    
    op.drop_table('cameras')
    
    op.drop_index('idx_users_email', 'users')
    op.drop_index('idx_users_username', 'users')
    
    op.drop_table('users')
